AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: rdklib
    Description: rdklib library for authoring Config Rules
    Author: awslabs
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.rst
    Labels: ['stable']
    HomePageUrl: https://github.com/awslabs/aws-config-rdklib
    SemanticVersion: 0.3.0
    SourceCodeUrl: https://github.com/awslabs/aws-config-rdklib

Description: >
  rdklib library for authoring Config Rules

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RdklibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: rdklib-layer
      Description: rdklib library for authoring Config Rules
      ContentUri: ./build
      CompatibleRuntimes:
        - python3.7
        - python3.8
        - python3.9
      LicenseInfo: 'Apache License, Version 2.0'

Outputs:
  RdklibLayerArn:
    Description: rdklib layer ARN
    Value: !Ref RdklibLayer
